name: crophealthai_mobile
description: AI-powered crop diagnosis in your pocket.
publish_to: "none" # this is not a pub package

version: 1.0.0+5

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0

  # Location & geolocation
  geolocator: ^10.1.1

  url_launcher: ^6.3.2

  # HTTP requests
  http: ^0.13.6

  # Persistent storage
  shared_preferences: ^2.5.3

  # Image picker
  image_picker: ^0.8.9

  # International phone field
  intl_phone_field: ^3.2.0

  pin_code_fields: ^8.0.1

  video_player: ^2.8.6
  chewie: ^1.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/bg_sunrise.jpeg
    - assets/logo.jpeg
    - assets/phone_verification.jpeg

  fonts:
    - family: Garamond
      fonts:
        - asset: fonts/EBGaramond-Regular.ttf