name: crophealthai_mobile
description: AI-powered crop diagnosis in your pocket
publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.1.7

  # Core
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  shared_preferences: ^2.5.3

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0

  # Device / Location
  geolocator: ^10.1.1
  image_picker: ^0.8.5+3

  # Country code + flags
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/bg_sunrise.png
    - assets/logo.jpeg
