// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXCe2au9Dmp6z9grB4OfcNrtAT97NLjYw',
    appId: '1:335031153474:web:476e5d564e411d06714edb',
    messagingSenderId: '335031153474',
    projectId: 'crophealthai-b3c04',
    authDomain: 'crophealthai-b3c04.firebaseapp.com',
    storageBucket: 'crophealthai-b3c04.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJKrK7ejnh4WFnMHlb2o_9Flc81Fv0G-g',
    appId: '1:335031153474:android:8864d78a044e6213714edb',
    messagingSenderId: '335031153474',
    projectId: 'crophealthai-b3c04',
    storageBucket: 'crophealthai-b3c04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs6wKr_BJfT70xvSEUkXk6_Q61cBwJzAE',
    appId: '1:335031153474:ios:8b06e9a9643bbe31714edb',
    messagingSenderId: '335031153474',
    projectId: 'crophealthai-b3c04',
    storageBucket: 'crophealthai-b3c04.firebasestorage.app',
    iosBundleId: 'com.example.crophealthaiMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs6wKr_BJfT70xvSEUkXk6_Q61cBwJzAE',
    appId: '1:335031153474:ios:8b06e9a9643bbe31714edb',
    messagingSenderId: '335031153474',
    projectId: 'crophealthai-b3c04',
    storageBucket: 'crophealthai-b3c04.firebasestorage.app',
    iosBundleId: 'com.example.crophealthaiMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXCe2au9Dmp6z9grB4OfcNrtAT97NLjYw',
    appId: '1:335031153474:web:476e5d564e411d06714edb',
    messagingSenderId: '335031153474',
    projectId: 'crophealthai-b3c04',
    authDomain: 'crophealthai-b3c04.firebaseapp.com',
    storageBucket: 'crophealthai-b3c04.firebasestorage.app',
  );
}
